# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    paths:
        - "control_system/*"
        - ".github/workflows/control_system.yml"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

defaults:
  run:
    working-directory: ./control_system/

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  CMAKE_PREFIX_PATH: /opt/openrobots:/usr/local:$CMAKE_PREFIX_PATH
  #PATH: /opt/openrobots/bin:$PATH
  #PKG_CONFIG_PATH: /opt/openrobots/lib/pkgconfig:$PKG_CONFIG_PATH
  PYTHONPATH: /usr/local/lib/python3.10/dist-packages:$PYTHONPATH
  LD_LIBRARY_PATH: /opt/openrobots/lib:$LD_LIBRARY_PATH

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v4
      - name: Prepare Dependencies for casadi
        run: |
          sudo apt-get update && sudo apt-get install -y libeigen3-dev
          sudo apt install -y git cmake build-essential wget curl liblapack-dev libblas-dev pkg-config gfortran python3-pip

      # Zenn alumina_type10 氏による スクラップ記事をもとにキャッシュ機構を実装する
      - name: casadi cache restore
        id: cache-casadi
        uses: actions/cache@v4
        env:
          cache-name: cache-casadi
        with:
          path: control_system/casadi
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('control_system/casadi/package.xml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - if: ${{ steps.cache-casadi.outputs.cache-hit != 'true' }}
        name: Build casadi
        run: |
          git clone -b 3.6.5 https://github.com/casadi/casadi.git
          cd casadi
          mkdir build && cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local -DWITH_IPOPT=ON -DWITH_OSQP=ON -DWITH_BUILD_REQUIRED=ON
          make -j$(nproc)

      - name: Install casadi
        run: |
          cd casadi/build
          sudo make install          

      - name: Prepare Dependencies for pinocchio
        run: |
          sudo apt install -qqy git libeigen3-dev libboost-all-dev liburdfdom-dev curl
          sudo sh -c "echo 'deb [arch=amd64] http://robotpkg.openrobots.org/packages/debian/pub $(lsb_release -cs) robotpkg' >> /etc/apt/sources.list.d/robotpkg.list"
          curl http://robotpkg.openrobots.org/packages/debian/robotpkg.key | sudo apt-key add -
          sudo apt-get update
          sudo apt install robotpkg-py310-eigenpy robotpkg-py310-casadi

      - name: pinocchio cache restore
        id: cache-pinocchio
        uses: actions/cache@v4
        env:
          cache-name: cache-pinocchio
        with:
          path: control_system/pinocchio
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('control_system/pinocchio/package.xml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      #- name: Build pinocchio
      # Zenn alumina_type10 氏による スクラップ記事をもとにキャッシュ機構を実装する
      # https://zenn.dev/link/comments/9b34b34878ea5f
      - if: ${{ steps.cache-pinocchio.outputs.cache-hit != 'true' }}
        name: Build pinocchio
        run: |
          git clone --recursive https://github.com/stack-of-tasks/pinocchio
          cd pinocchio
          git checkout v3.0.0
          mkdir build && cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local -DBUILD_DOCUMENTATION=OFF -DBUILD_TESTING=OFF -DPYTHON_EXECUTABLE=/usr/bin/python3 -DBUILD_WITH_CASADI_SUPPORT=ON
          make -j$(nproc)

      - name: Install pinocchio
        run: |
          cd pinocchio/build
          sudo make install

      - name: Install python package
        run: |
          pip3 install casadi

      - name: Test env
        run: |
          export PYTHONPATH=/usr/local/lib/python3.10/dist-packages:$PYTHONPATH
          python3 test_env.py

